# Generated by Django 2.1.5 on 2019-03-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('temperature', models.IntegerField()),
                ('location', models.CharField(max_length=150)),
                ('cover_img', models.ImageField(upload_to='')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
            ],
            options={
                'ordering': ['create_at'],
            },
        ),
    ]
